In [ ]:
from utils.serialize import read_jsonl, kg_from_dict
from utils.graph import KnowledgeGraph
from utils.concept import ConceptGraph

import random

/people/boufouss/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [2]:
concept = ConceptGraph(device="cuda:1")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
#P = KnowledgeGraph("John has a cat.", triples=[('john', 'HasA', 'cat')])
#H = KnowledgeGraph("John has an animal.", triples=[('john', 'HasA', 'animal')])

In [3]:
PATH = "out/anli_dev_r1/graphs.jsonl"
LABELS = {0: "entailment", 1: "neutral", 2: "contradiction"}
rows = list(read_jsonl(PATH))
len_rows = len(rows)
print(len_rows)

1000

In [10]:
random.seed(84)

In [11]:
rnd = random.randint(0, len_rows)
print(rnd)

row = rows[rnd]

749

In [12]:
P = kg_from_dict({"text": row["premise"],    "triples": row["premise_triples"]})
H = kg_from_dict({"text": row["hypothesis"], "triples": row["hypothesis_triples"]})
print(f"P : {P.get_text()}\nH : {H.get_text()}\nlabel : {LABELS[row['label']]}")

P : John Thomas Ward (born in Timaru, Canterbury, on 11 March 1937) is a former New Zealand cricketer who played as a wicket-keeper in 8 Tests from 1964 to 1968. Ward's Test captain John Reid said, "He was easily the best wicketkeeper in New Zealand in his time, but was plagued by injury."
H : John Thomas Ward was born in 19377
label : contradiction

In [13]:
H.get_rel() - P.get_rel()

{('bear', 'AtTime', '1937')}

In [14]:
data_f = concept.get_relevant_data(P, H, threshold_link=0.3, threshold_path=0.5, forward= True, dist = 2)
data_f[0]

Empty DataFrame
Columns: [id_path, head, rel, tail, score_link, info_scored]
Index: []

In [15]:
"""
P.augment(data_p[0])
P.display()
"""
data_f[1]

Empty DataFrame
Columns: [id_path, score_path]
Index: []

In [16]:
data_b = concept.get_relevant_data(P, H, threshold_link=0.3, threshold_path=0.5, forward= False, dist = 1)
data_b[0]

Empty DataFrame
Columns: [id_path, head, rel, tail, score_link, info_scored]
Index: []

In [17]:
"""
H.augment(data_h[0])
H.display()
"""
data_b[1]

Empty DataFrame
Columns: [id_path, score_path]
Index: []

In [32]:
concept.get_rel_nodes([""])

Empty DataFrame
Columns: [head_word, relation, tail_word, weight]
Index: []